---
# group_vars/all.yml
 
region: us-east-1
zone: us-east-1e # zone that the master AMI will be configured in
keypair: testkp
security_groups: ['default']
#instance_type: t2.micro
instance_type: m1.small
vpc_subnet_id: subnet-1ec0f723
tenancy: dedicated

# specify group_name on the command line with -e group_name=devX
group_name: test
instances_min: 1 # minimum number of instances in the auto scaling group
instances_max: 3 # maximum number of instances in the auto scaling group
iam_profile: "noaccess"
volumes:
  - device_name: /dev/sda1
    device_type: gp2
    volume_size: 8 # size of the root disk
    delete_on_termination: true



#env: "staging" # env name, this will be used as an inventory file name
#app_code_user: "ubuntu" # remote user
#aws_region: eu-central-1 # AWS region, where instance will be created
#instance_type: t2.micro  # AWS instance type
ami: ami-7209f41f   # AMI id, example uses Ubuntu 14.04.1 LTS


##Define Domain name (Can't be blank)
#domain_name : 'TODO'

#Define datacenter environment (Can't be blank)
#dc_env : 'TODO'
#env : test-env
#aws_access_key: 'TODO'
#aws_secret_key: 'TODO'

##Environment variables
#vpc_name :  Staging-VPC
#aws_region :  ap-southeast-1
#resource_tags : { "Name":"Staging-VPC" }
#cidr_block : 10.0.0.0/16

#Subnet-web
#cidr_web_1 : 10.0.1.0/24
#az_web_1: ap-southeast-1a
#cidr_web_2 : 10.0.2.0/24
#az_web_2: ap-southeast-1b
#resource_tags_web_1 : { "Name":"Staging-ap-southeast-1a", "Environment":"Staging", "Service" : "Web" }
#resource_tags_web_2 : { "Name":"Staging-ap-southeast-1b", "Environment":"Staging", "Service" : "Web" }
#vpc_id :  'TODO'

#ELB
#elb_url : 'TODO'

##System variables (Can't be blank)
#Define Time Zone
#timezone : Asia/Calcutta

#Define global ssh user (Can't be blank)
#ansible_ssh_user : navigator

#Define private key
#ansible_ssh_private_key_file : 'TODO'
#id_rsa : 'TODO'
#id_rsa_pub : 'TODO'

##Project repo
#project_repo : 'TODO'
#project_doc_root : 'TODO'

#Kafka
#kafka_url : http://mirror.cc.columbia.edu/pub/software/apache/kafka/0.8.2.1/kafka_2.11-0.8.2.1.tgz

#Kafka-manager
#kafka_manager_url : ~/kafka-manager-1.2.7.zip

#Kibana
#kibana_url : https://download.elastic.co/kibana/kibana/kibana-4.1.2-linux-x64.tar.gz


