---
# move to specific group_vars dirs.. 
volumes:
  - device_name: /dev/sda1
    device_type: gp2
    volume_size: 8 # size of the root disk
    delete_on_termination: true

assign_public_ip: yes
instance_type: m3.medium
keypair: ansibletest
security_groups: ['sg_cluster_master']
vpc_subnet_id: subnet-657f293d
group_name: cluster_master_group

#iam_profile: "noaccess"
