---
- name: Launch new instance
  ec2:
    region: "{{ region }}"
    keypair: "{{ keypair }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: "{{ assign_public_ip }}"
    tenancy: "{{ tenancy }}"
    zone: "{{ zone }}"
    group: "{{ security_groups }}"
    image: "{{ ami }}"
    count: "{{ count }}"
    instance_type: "{{ instance_type }}"
    instance_tags:
      Name: "{{ name }}"
      Foo: Bar
      ClusterType: Master
    volumes: "{{ volumes }}"
    wait: yes
  register: ec2

- name: Add new instances to host group
  add_host:
    name: "{{ item.public_ip }}"
    groups: "{{ name }}"
    ec2_id: "{{ item.id }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for instance to boot
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 30
    timeout: 300
    state: started
  with_items: "{{ ec2.instances }}"

- name: Gather facts
  ec2_remote_facts:
    region: "{{ region }}"
    filters:
      "tag:ClusterType": Master
      instance-state-name: running
  tags: facts
  register: remotefacts

- name: Remote Facts
  debug:
    msg="{{remotefacts}}"
  tags: facts

